projetoOrientacoes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('relatorio/', include('relatorio.urls')),
    path('tarefa/', include('tarefa.urls')),
    path('trabalhos/', include('trabalho.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('webpage.urls')),

]

tarefa/urls.py
from django.urls import path, include
from .views import TarefaView, TarefaListView, TarefaUpdateView, TarefaDeleteView, TarefaDetailView

urlpatterns = [
    path('cadastrar/<str:token>', TarefaView.as_view(), name='tarefa_cadastrar'),
    path('listar/<str:token>', TarefaListView.as_view(), name='tarefa_listar'),
    path('editar/<int:pk>', TarefaUpdateView.as_view(), name='tarefa_update'),
    path('deletar/<int:pk>/', TarefaDeleteView.as_view(), name='tarefa_delete'),
    path('detalhe/<int:pk>/', TarefaDetailView.as_view(), name='tarefa_detalhe'),

]

trabalho/urls.py
from django.urls import path, include
from .views import TrabalhoCreate, TrabalhoListView, TrabalhoUpdateView, TrabalhoDeleteView, TrabalhoDetailView

urlpatterns = [
    path('cadastrar/', TrabalhoCreate.as_view(), name='trabalho_cadastrar'),
    path('listar/', TrabalhoListView.as_view(), name='trabalho_listar'),
    path('editar/<int:pk>', TrabalhoUpdateView.as_view(), name='trabalho_update'),
    path('deletar/<int:pk>/', TrabalhoDeleteView.as_view(), name='trabalho_delete'),
    path('detalhe/<int:pk>/', TrabalhoDetailView.as_view(), name='trabalho_detalhe'),

]

trabalho/models.py
from django.db import models

from core.models import Area, Tipo, TipoTarefa


# Vamos aprender juntos kk!
class Trabalho(models.Model):
    id = models.AutoField(primary_key=True, db_column="id_trabalho")
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    data_cadastro = models.DateField('Data de cadastro', auto_now_add=True)
    data_inicio = models.DateField(blank=True, null=True, db_column="data_inicio")
    data_entrega = models.DateField(blank=True, null=True, db_column="data_entrega")
    # nome_aluno = models.CharField(max_length=255, blank=True, null=True)
    # email_aluno = models.EmailField('E-mail')
    token = models.CharField(max_length=100)
    id_usuario = models.ForeignKey("accounts.CustomUsuario", on_delete=models.CASCADE, db_column="id_usuario")
    area = models.ForeignKey(Area, models.DO_NOTHING, db_column='id_area', blank=True, null=True)
    tipo = models.ForeignKey(Tipo, models.DO_NOTHING, db_column='id_tipo', blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.nome, self.area)

    class Meta:
        db_table = "trabalho"
        managed = True

trabalho/forms.py
from django import forms

from trabalho.models import Trabalho


class TrabalhoModelForm(forms.ModelForm):
    class Meta:
        model = Trabalho
        fields = ['nome', 'descricao', 'data_inicio', 'data_entrega', 'area', 'tipo']

trabalho/views.py
from secrets import token_urlsafe

from django.core.mail import send_mail
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from core.models import Area, Tipo
from trabalho.forms import TrabalhoModelForm
from trabalho.models import Trabalho


class TrabalhoCreate(CreateView):
    model = Trabalho
    form_class = TrabalhoModelForm
    template_name = 'trabalho/new-trabalho.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['areas'] = list(Area.objects.all())
        context['tipos'] = list(Tipo.objects.all())
        return context

    def form_valid(self, form):
        trabalho = form.save(commit=False)
        trabalho.id_usuario = self.request.user
        token = token_urlsafe(16)
        trabalho.token = token
        trabalho.save()
        usuario = self.request.user
        data = {'usuario': usuario, 'trabalho': trabalho}
        plain_text = render_to_string('trabalho/emails/email.txt', data)
        html_email = render_to_string('trabalho/emails/email.html', data)
        send_mail("Novo Trabalho",
                  plain_text,
                  "sigoorientacoes@gmail.com",
                  ['{0}'.format(self.request.user)],
                  html_message=html_email
                  )
        return super(TrabalhoCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('index')


class TrabalhoListView(ListView):
    model = Trabalho

    def get_queryset(self):
        # trabalhos = Trabalho.objects.all()
        trabalhos = Trabalho.objects.order_by('nome').filter(id_usuario=self.request.user)
        # print(self.request.user)
        return trabalhos


class TrabalhoUpdateView(UpdateView):
    model = Trabalho
    form_class = TrabalhoModelForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse('trabalho_listar')


class TrabalhoDeleteView(DeleteView):
    model = Trabalho

    def get_success_url(self):
        return reverse('trabalho_listar')


class TrabalhoDetailView(DetailView):
    model = Trabalho
    fields = ['nome', 'descrição', 'area']

trabalho/templates/trabalho/new-trabalho.html
{% extends 'base.html' %}
{% block title %}SiGO - Cadastro de Trabalhos{% endblock title %}
{% block card-title %}Cadastre{% endblock card-title %}

{% block content %}

{% block titlePagina %}<h1 class="mt-4">Cadastrar Trabalho</h1>{% endblock titlePagina %}
<div class="card" style="margin-top:20px;">

    <div class="card-body">
        <form method="post" class="form" autocomplete="off">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-lg-12 mb-3">
                    <label>Nome</label>
                    <input class="form-control" id="id_nome" name="nome"
                           type="text" value="{{request.POST.nome}}"
                           placeholder="Digite o nome do trabalho"
                           required>
                </div>
            </div>

            <!--<p>{{ user.id }}</p>-->
            <div class="form-row">
                <div class="form-group col-lg-12 mb-3">
                    <label for="id_descricao">Descricao</label>

                    <textarea class="form-control" name="descricao" cols="40" rows="10" id="id_descricao"
                              required> </textarea>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-lg-6 mb-3">

                    <label for="id_data_inicio">Data inicio</label>
                    <input type="date" class="form-control" name="data_inicio" id="id_data_inicio">
                </div>

                <div class="form-group col-lg-6 mb-3">
                    <label for="id_data_entrega">Data entrega</label>
                    <input type="date" class="form-control" name="data_entrega" id="id_data_entrega">
                </div>
            </div>


            <div class="form-row">

                <div class="form-group col-lg-6 mb-3">
                    <label for="id_area">Area</label>
                    <select class="form-control" name="area" id="id_area">
                        <option value="" selected="">---------</option>
                        {% for area in areas %}
                        <option value="{{ area.id }}">{{ area.nome }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group col-lg-6 mb-3">
                    <label for="id_tipo">Tipo</label>
                    <select class="form-control" name="tipo" id="id_tipo">
                        <option value="" selected="">---------</option>
                        {% for tipo in tipos %}
                        <option value="{{ tipo.id }}">{{ tipo.nome }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Cadastrar</button>
        </form>
    </div>
</div>
{% endblock %}

trabalho/templates/trabalho/trabalho_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
{% block titlePagina %}<h1 class="mt-4">Confirmar exclusão</h1>{% endblock titlePagina %}
<div class="card" style="margin-top:20px;">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <h2>Você realmente tem o desejo de excluir o Trabalho {{ object }}?</h2>
            {{form}}
            <input class="btn btn-danger" type="submit" value="Confirmar">
        </form>
    </div>
</div>
{% endblock %}

trabalho/templates/trabalho/trabalho_detail.html
{% extends 'base.html'%}

{% block content %}
{% block titlePagina %}<h1 class="mt-4">Detalhe do Trabalho</h1>{% endblock titlePagina %}
<div class="card" style="margin-top:20px;">
    <div class="card-body">
        <div class="container-fluid" style="margin-top:20px;">
            <div class="row text-center">
                <h4 class="col-lg-12 mb-3">{{object.nome}}</h4>
            </div>
        </div>

        <p class="card-text">{{ trabalho.descricao }}</p>
    </div>
</div>

{% endblock %}

trabalho/templates/trabalho/trabalho_list.html
{% extends 'base.html' %}
{% block title %}SiGO - Cadastro de Trabalhos{% endblock title %}

{% block content %}
{% if object_list %}
{% block titlePagina %}<h1 class="mt-4">Trabalhos</h1>{% endblock titlePagina %}

{% block card-title %}Lista de Trabalhos{% endblock card-title %}
{%for trabalho in object_list%}
<div class="card" style="margin-top:20px;">
    <div class="card-header">

        <div class="form-group row mb-0 mt-0">
            <div class="col-6">
                <h3>{{ trabalho.nome }}</h3>
            </div>
            <div class="col-6">
                <div class="btn-group float-right">
                    <a class="btn mr-6" style="color:black;" href="{%url 'trabalho_delete' trabalho.id%}">
                        <i class="fas fa-trash-alt" title="Excluir Trabalho"></i></a>
                </div>
                <div class="btn-group float-right">
                    <a class="btn mr-6" style="color:black;"
                       href="{%url 'trabalho_update' trabalho.id%}"><i class="fas fa-edit" title="Editar Trabalho"></i></a>
                </div>

                <div class="btn-group float-right">
                    <a class="btn mr-6" style="color:black;"
                       href="{%url 'trabalho_detalhe' trabalho.id%}"><i class="fas fa-eye"
                                                                        title="Detalhes do Trabalho"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <p class="card-text">{{ trabalho.descricao }}</p>
    </div>
    <div class="footer" style="margin: 20px;">

        <div class="btn-group">
            <a class="btn btn-success mr-3" style="color:#ffffff;"
               href="{%url 'tarefa_cadastrar' trabalho.token%}"><i class="fas fa-plus"></i> Tarefa</a>
        </div>

        <div class="btn-group">
            <a class="btn btn-success mr-3" style="color:#ffffff;"
               href="{%url 'tarefa_listar' trabalho.token%}"><i
                    class="fas fa-list-alt"></i> Tarefa(s)</a>

        </div>

    </div>
</div>
{% endfor %}
{% else %}
<h3 class="text-center">Você não possui trabalhos!</h3>

{% endif %}
{% endblock %}

trabalho/templates/trabalho/trabalho_update_form.html
{% extends 'base.html' %}
{% block title %}SiGO - Cadastro de Trabalhos{% endblock title %}
{% block card-title %}Editar{% endblock card-title %}

{% block content %}
{% block titlePagina %}<h1 class="mt-4">Atualizar Trabalho</h1>{% endblock titlePagina %}
<div class="card" style="margin-top:20px;">
    <div class="card-body">
        <form method="post" class="form">
            {% csrf_token %}
            <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
            <div class="form-row">
                <div class="form-group col-lg-12 mb-3">
                    <label>Nome</label>
                    <input class="form-control" id="id_nome" name="nome"
                           type="text" value="{{ form.nome.value }}"
                           required>
                </div>
            </div>

            <!--<p>{{ user.id }}</p>-->
            <div class="form-row">
                <div class="form-group col-lg-12 mb-3">
                    <label for="id_descricao">Descricao</label>

                    <textarea class="form-control" name="descricao" cols="40" rows="10" id="id_descricao"
                              value="{{ form.descricao.value }}" required>{{ form.descricao.value }} </textarea>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-lg-6 mb-3">

                    <label for="id_data_inicio">Data inicio</label>
                    <input type="date" class="form-control" name="data_inicio"
                           value="{{ form.data_inicio.value|date:'Y-m-d'}}"
                           id="id_data_inicio">
                </div>

                <div class="form-group col-lg-6 mb-3">
                    <label for="id_data_entrega">Data entrega</label>
                    <input type="date" class="form-control" name="data_entrega" id="id_data_entrega"
                           value="{{ form.data_inicio.value|date:'Y-m-d'}}">
                </div>
            </div>


            <div class="form-row">

                <div class="form-group col-lg-6 mb-3">
                    <label for="id_area">Area</label>
                    <select class="form-control" name="area" id="id_area">
                        <option value="" selected="">---------</option>
                        {% for field in form.area %}
                        <tr>
                            <td>{{field}}</td>
                        </tr>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group col-lg-6 mb-3">
                    <label for="id_tipo">Tipo</label>
                    <select class="form-control" name="tipo" id="id_tipo">
                        <option value="" selected="">---------</option>
                        {% for field in form.tipo %}
                        <tr>
                            <td>{{field}}</td>
                        </tr>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i>  Cadastrar</button>
        </form>
    </div>
</div>

{% endblock %}