projetoOrientacoes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('relatorio/', include('relatorio.urls')),
    path('tarefa/', include('tarefa.urls')),
    path('trabalhos/', include('trabalho.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('webpage.urls')),

]

tarefa/urls.py
from django.urls import path, include
from .views import TarefaView, TarefaListView, TarefaUpdateView, TarefaDeleteView, TarefaDetailView

urlpatterns = [
    path('cadastrar/<str:token>', TarefaView.as_view(), name='tarefa_cadastrar'),
    path('listar/<str:token>', TarefaListView.as_view(), name='tarefa_listar'),
    path('editar/<int:pk>', TarefaUpdateView.as_view(), name='tarefa_update'),
    path('deletar/<int:pk>/', TarefaDeleteView.as_view(), name='tarefa_delete'),
    path('detalhe/<int:pk>/', TarefaDetailView.as_view(), name='tarefa_detalhe'),

]

tarefa/models.py
from django.db import models

from django.db import models

from core.models import Area, Tipo, TipoTarefa

# Vamos aprender juntos kk!
from trabalho.models import Trabalho


class Tarefa(models.Model):
    id = models.AutoField(primary_key=True, db_column="id_tarefa")
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    data_cadastro = models.DateField('Data de cadastro', auto_now_add=True)
    data_realizacao = models.DateField(blank=True, null=True, db_column="data_realizacao")
    tipo_tarefa = models.ForeignKey(TipoTarefa, models.DO_NOTHING, db_column='id_tipo', blank=True, null=True)
    trabalho = models.ForeignKey(Trabalho, models.DO_NOTHING, db_column='id_trabalho', blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.nome)

    class Meta:
        db_table = "tarefa"
        managed = True

tarefa/forms.py
from django import forms

from tarefa.models import Tarefa


class TarefaModelForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = ['nome', 'descricao', 'data_realizacao', 'tipo_tarefa']

tarefa/views.py
from django.shortcuts import render

from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from core.models import TipoTarefa
from tarefa.forms import TarefaModelForm
from tarefa.models import Tarefa
from trabalho.models import Trabalho


class TarefaView(CreateView):
    model = Tarefa
    form_class = TarefaModelForm
    template_name = 'tarefa/new-tarefa.html'
    success_message = "Tarefa cadastrada com sucesso!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tipo_tarefas'] = list(TipoTarefa.objects.all())

        return context

    def form_valid(self, form):
        tarefa = form.save(commit=False)
        token = self.kwargs.get("token")
        trabalho_id = Trabalho.objects.get(token=token)
        tarefa.trabalho = trabalho_id
        tarefa.save()
        return super(TarefaView, self).form_valid(form)

    def get_success_url(self):
        return reverse('index')


class TarefaListView(ListView):
    model = Tarefa
    template_name = 'tarefa/tarefa_listar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        token = self.kwargs.get("token")
        context['trabalho'] = list(Trabalho.objects.filter(token=token))
        return context

    def get_queryset(self):
        token = self.kwargs.get("token")
        trabalho_id = list(trabalho.id for trabalho in Trabalho.objects.filter(token=token))
        tarefa = Tarefa.objects.filter(trabalho__in=trabalho_id)
        return tarefa


class TarefaUpdateView(UpdateView):
    model = Tarefa
    form_class = TarefaModelForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        id_tarefa = self.kwargs.get("pk")
        tarefa_id = list(tarefa.trabalho.id for tarefa in Tarefa.objects.filter(id=id_tarefa))
        trabalho = Trabalho.objects.filter(id__in=tarefa_id)

        for member in trabalho.iterator():
            token = member.token

        return reverse('tarefa_listar', args=[token])


class TarefaDeleteView(DeleteView):
    model = Tarefa

    def get_success_url(self):
        id_tarefa = self.kwargs.get("pk")
        tarefa_id = list(tarefa.trabalho.id for tarefa in Tarefa.objects.filter(id=id_tarefa))
        trabalho = Trabalho.objects.filter(id__in=tarefa_id)

        for member in trabalho.iterator():
            token = member.token

        return reverse('tarefa_listar', args=[token])


class TarefaDetailView(DetailView):
    model = Tarefa
    fields = ['nome', 'descrição', 'data_realizacao', 'tipo_tarefa', 'trabalho']

tarefa/templates/tarefa/new-tarefa.html
{% extends 'base.html' %}
{% block title %}SiGO - Cadastro de Tarefa{% endblock title %}
{% block card-title %}Cadastre sua tarefa{% endblock card-title %}

{% block content %}

{% block titlePagina %}<h1 class="mt-4">Cadastrar Tarefa</h1>{% endblock titlePagina %}
<div class="card" style="margin-top:20px;">
    <div class="card-body">
        <form method="post" class="form" autocomplete="off">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-lg-12 mb-3">
                    <label>Nome</label>
                    <input class="form-control" id="id_nome" name="nome"
                           type="text" value="{{request.POST.nome}}"
                           placeholder="Digite o nome tarefa"
                           required>
                </div>
            </div>

            <!--<p>{{ user.id }}</p>-->
            <div class="form-row">
                <div class="form-group col-lg-12 mb-3">
                    <label for="id_descricao">Descricao</label>

                    <textarea class="form-control" name="descricao" cols="40" rows="10" id="id_descricao"
                              required> </textarea>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-lg-6 mb-3">

                    <label for="id_data_realizacao">Data realização</label>
                    <input type="date" class="form-control" name="data_realizacao" id="id_data_realizacao">
                </div>

                <div class="form-group col-lg-6 mb-3">
                    <label for="id_tipo_tarefa">Tipo da Tarefa</label>
                    <select class="form-control" name="tipo_tarefa" id="id_tipo_tarefa">
                        <option value="" selected="">---------</option>
                        {% for tipo in tipo_tarefas %}
                        <option value="{{ tipo.id }}">{{ tipo.nome }}</option>
                        {% endfor %}
                    </select>
                </div>

            </div>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
</div>

{% endblock %}

tarefa/templates/tarefa/tarefa_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
{% block titlePagina %}<h1 class="mt-4">Confirmar Exclusão</h1>{% endblock titlePagina %}
<div class="card" style="margin-top:20px;">
    <div class="card-body">
<form method="post">
    {% csrf_token %}
    <h2>Você realmente tem o desejo de excluir a Tarefa {{ object }}?</h2>
    {{form}}
    <input class="btn btn-danger" type="submit" value="Confirmar">
</form>    

{% endblock %}

tarefa/templates/tarefa/tarefa_detail.html
{% extends 'base.html'%}

{% block content %}
{% block titlePagina %}<h1 class="mt-4">Detalhe da Tarefa</h1>{% endblock titlePagina %}
<div class="card" style="margin-top:20px;">
    <div class="card-body">
        <div class="container-fluid" style="margin-top:20px;">
            <div class="row text-center">
                <h4 class="col-lg-12 mb-3">{{object.nome}}</h4>
            </div>
            <div class="row text-center">
                <p class="card-text">{{ object.descricao }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tarefa/templates/tarefa/tarefa_listar.html
{% extends 'base.html' %}
{% block title %}SiGO - Cadastro de Trabalhos{% endblock title %}

{% block content %}
{% if object_list %}
{%for trab in trabalho%}
{% block titlePagina %}<h1 class="mt-4">Lista de Tarefas - {{ trab.nome }}</h1>{% endblock titlePagina %}
{% endfor %}
{%for tarefa in object_list%}
<div class="card" style="margin-top:20px;">
    <div class="card-header">
        <h3>{{ tarefa.nome }}</h3>
    </div>
    <div class="card-body">
        <div class="form-group row mb-0 mt-0">
            <div class="col-6">
                <h3>{{ tarefa.descricao }}</h3>
            </div>
            <div class="col-6">
                <div class="btn-group float-right">
                    <a class="btn mr-6" style="color:black;" href="{%url 'tarefa_delete' tarefa.id%}">
                        <i class="fas fa-trash-alt" title="Excluir Tarefa"></i></a>
                </div>

                <div class="btn-group float-right">
                    <a class="btn mr-6" style="color:black;"
                       href="{%url 'tarefa_update' tarefa.id%}"><i class="fas fa-edit" title="Editar Tarefa"></i></a>
                </div>

                <div class="btn-group float-right">
                    <a class="btn mr-6" style="color:black;"
                       href="{%url 'tarefa_detalhe' tarefa.id%}"><i class="fas fa-eye"
                                                                    title="Detalhes do Tarefa"></i></a>
                </div>

            </div>

        </div>
        <div class="footer" style="margin: 20px;">


        </div>
    </div>
</div>
{% endfor %}
{% else %}

{%for trab in trabalho%}
<h3 class="text-center">Você não possui tarefas para o trabalhoi {{ trab.nome }}!</h3>
{% endfor %}
{% endif %}
{% endblock %}

tarefa/templates/tarefa/tarefa_update_form.html
{% extends 'base.html' %}
{% block title %}SiGO - Atualizar Tarefa{% endblock title %}
{% block card-title %}Atualizar sua tarefa{% endblock card-title %}

{% block content %}

{% block titlePagina %}<h1 class="mt-4">Atualizar tarefa</h1>{% endblock titlePagina %}
<div class="card" style="margin-top:20px;">
    <div class="card-body">
        <form method="post" class="form" autocomplete="off">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-lg-12 mb-3">
                    <label>Nome</label>
                    <input class="form-control" id="id_nome" name="nome"
                           type="text" value="{{ form.nome.value }}"
                           placeholder="Digite o nome tarefa"
                           required>
                </div>
            </div>

            <!--<p>{{ user.id }}</p>-->
            <div class="form-row">
                <div class="form-group col-lg-12 mb-3">
                    <label for="id_descricao">Descricao</label>

                    <textarea class="form-control" name="descricao" cols="40" rows="10" id="id_descricao"
                              value="{{ form.descricao.value }}" required>{{ form.descricao.value }} </textarea>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-lg-6 mb-3">

                    <label for="id_data_realizacao">Data realização</label>
                    <input type="date" class="form-control" name="data_realizacao" id="id_data_realizacao"
                           value="{{ form.ata_realizacao.value|date:'Y-m-d'}}">
                </div>

                <div class="form-group col-lg-6 mb-3">
                    <label for="id_tipo_tarefa">Tipo tarefa</label>
                    <select class="form-control" name="tipo_tarefa" id="id_tipo_tarefa">
                        <option value="" selected="">---------</option>
                        {% for field in form.tipo_tarefa %}
                        <tr>
                            <td>{{field}}</td>
                        </tr>
                        {% endfor %}
                    </select>
                </div>

            </div>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
</div>
{% endblock %}